src/account/urls.py
##############################################################################
# Copyright (c) 2016 Max Breitenfeldt and others.
# Copyright (c) 2018 Parker Berberian, Sawyer Bergeron, and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################


"""
laas_dashboard URL Configuration.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.10/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url
from django.urls import path

from account.views import (
    AccountSettingsView,
    JiraAuthenticatedView,
    JiraLoginView,
    OIDCLoginView,
    JiraLogoutView,
    UserListView,
    account_resource_view,
    account_booking_view,
    account_images_view,
    account_configuration_view,
    account_detail_view,
    resource_delete_view,
    booking_cancel_view,
    image_delete_view,
    configuration_delete_view
)

from laas_dashboard import settings


def get_login_view():
    if (settings.AUTH_SETTING == 'LFID'):
        return OIDCLoginView.as_view()
    else:
        return JiraLoginView.as_view()


app_name = "account"
urlpatterns = [
    url(r'^settings/', AccountSettingsView.as_view(), name='settings'),
    url(r'^authenticated/$', JiraAuthenticatedView.as_view(), name='authenticated'),
    url(r'^login/$', get_login_view(), name='login'),
    url(r'^logout/$', JiraLogoutView.as_view(), name='logout'),
    url(r'^users/$', UserListView.as_view(), name='users'),
    url(r'^my/resources/$', account_resource_view, name="my-resources"),
    path('my/resources/delete/<int:resource_id>', resource_delete_view),
    url(r'^my/bookings/$', account_booking_view, name="my-bookings"),
    path('my/bookings/cancel/<int:booking_id>', booking_cancel_view),
    url(r'^my/images/$', account_images_view, name="my-images"),
    path('my/images/delete/<int:image_id>', image_delete_view),
    url(r'^my/configurations/$', account_configuration_view, name="my-configurations"),
    path('my/configurations/delete/<int:config_id>', configuration_delete_view),
    url(r'^my/$', account_detail_view, name="my-account"),
]

src/api/urls.py
##############################################################################
# Copyright (c) 2016 Max Breitenfeldt and others.
# Copyright (c) 2018 Sawyer Bergeron, Parker Berberian, and others
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################


"""
laas_dashboard URL Configuration.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.10/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url
from django.urls import path

from api.views import (
    lab_profile,
    lab_status,
    lab_inventory,
    lab_downtime,
    specific_job,
    specific_task,
    new_jobs,
    current_jobs,
    done_jobs,
    update_host_bmc,
    lab_host,
    get_pdf,
    get_idf,
    lab_users,
    lab_user,
    GenerateTokenView,
    analytics_job
)

urlpatterns = [
    path('labs/<slug:lab_name>/profile', lab_profile),
    path('labs/<slug:lab_name>/status', lab_status),
    path('labs/<slug:lab_name>/inventory', lab_inventory),
    path('labs/<slug:lab_name>/downtime', lab_downtime),
    path('labs/<slug:lab_name>/hosts/<slug:host_id>', lab_host),
    path('labs/<slug:lab_name>/hosts/<slug:host_id>/bmc', update_host_bmc),
    path('labs/<slug:lab_name>/booking/<int:booking_id>/pdf', get_pdf, name="get-pdf"),
    path('labs/<slug:lab_name>/booking/<int:booking_id>/idf', get_idf, name="get-idf"),
    path('labs/<slug:lab_name>/jobs/<int:job_id>', specific_job),
    path('labs/<slug:lab_name>/jobs/<int:job_id>/<slug:task_id>', specific_task),
    path('labs/<slug:lab_name>/jobs/new', new_jobs),
    path('labs/<slug:lab_name>/jobs/current', current_jobs),
    path('labs/<slug:lab_name>/jobs/done', done_jobs),
    path('labs/<slug:lab_name>/jobs/getByType/DATA', analytics_job),
    path('labs/<slug:lab_name>/users', lab_users),
    path('labs/<slug:lab_name>/users/<int:user_id>', lab_user),
    url(r'^token$', GenerateTokenView.as_view(), name='generate_token'),
]

src/booking/urls.py
##############################################################################
# Copyright (c) 2016 Max Breitenfeldt and others.
# Copyright (c) 2018 Parker Berberian, Sawyer Bergeron, and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################


"""
laas_dashboard URL Configuration.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.10/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url

from booking.views import (
    booking_detail_view,
    BookingDeleteView,
    bookingDelete,
    BookingListView,
    booking_stats_view,
    booking_stats_json,
    quick_create,
    booking_modify_image
)

app_name = "booking"
urlpatterns = [
    url(r'^detail/(?P<booking_id>[0-9]+)/$', booking_detail_view, name='detail'),
    url(r'^(?P<booking_id>[0-9]+)/$', booking_detail_view, name='booking_detail'),
    url(r'^delete/$', BookingDeleteView.as_view(), name='delete_prefix'),
    url(r'^delete/(?P<booking_id>[0-9]+)/$', BookingDeleteView.as_view(), name='delete'),
    url(r'^delete/(?P<booking_id>[0-9]+)/confirm/$', bookingDelete, name='delete_booking'),
    url(r'^modify/(?P<booking_id>[0-9]+)/image/$', booking_modify_image, name='modify_booking_image'),
    url(r'^list/$', BookingListView.as_view(), name='list'),
    url(r'^stats/$', booking_stats_view, name='stats'),
    url(r'^stats/json$', booking_stats_json, name='stats_json'),
    url(r'^quick/$', quick_create, name='quick_create'),
]

src/dashboard/urls.py
##############################################################################
# Copyright (c) 2016 Max Breitenfeldt and others.
# Copyright (c) 2018 Sawyer Bergeron, Parker Berberian, and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################


"""
laas_dashboard URL Configuration.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.10/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url
from dashboard.views import (
    landing_view,
    lab_list_view,
    lab_detail_view,
    host_profile_detail_view
)

app_name = "dashboard"
urlpatterns = [
    url(r'^$', landing_view, name='index'),
    url(r'^lab/$', lab_list_view, name='all_labs'),
    url(r'^lab/(?P<lab_name>.+)/$', lab_detail_view, name='lab_detail'),
    url(r'^hosts/$', host_profile_detail_view, name="hostprofile_detail")
]

src/laas_dashboard/urls.py
##############################################################################
# Copyright (c) 2016 Max Breitenfeldt and others.
# Copyright (c) 2018 Sawyer Bergeron, Parker Berberian, and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################


"""
laas_dashboard URL Configuration.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.10/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin


urlpatterns = [

    url(r'^workflow/', include('workflow.urls', namespace='workflow')),
    url(r'^', include('dashboard.urls', namespace='dashboard')),
    url(r'^booking/', include('booking.urls', namespace='booking')),
    url(r'^accounts/', include('account.urls', namespace='account')),
    url(r'^resource/', include('resource_inventory.urls', namespace='resource')),
    url(r'^admin/', admin.site.urls),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^api/', include('api.urls')),
    url(r'^messages/', include('notifier.urls', namespace='notifier')),
    url(r'^oidc/', include('mozilla_django_oidc.urls')),
]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/notifier/urls.py
##############################################################################
# Copyright (c) 2018 Sawyer Bergeron, Parker Berberian, and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################


from django.conf.urls import url

from notifier.views import InboxView, NotificationView

app_name = "notifier"
urlpatterns = [
    url(r'^$', InboxView, name='messages'),
    url(r'^notification/(?P<notification_id>[0-9]+)/$', NotificationView, name='notifier_single')
]

src/templates/base/base.html
{% extends "layout.html" %}
{% load bootstrap4 %}
{% load staticfiles %}
{% block extrahead %}


<!-- Custom CSS -->
<link href="{% static "css/base.css" %}" rel="stylesheet">
<script src="/static/js/dashboard.js"></script>

{% endblock %}
{% block basecontent %}
<div id="wrapper" class="d-flex flex-column">
    <!-- Navigation -->
    {% block bgColor %}
    <nav class="navbar navbar-light bg-light navbar-fixed-top border-bottom py-0 mb-0" role="navigation">
    {% endblock bgColor %}
        <div class="container-fluid pb-2 pb-sm-0">
            <!-- Logo -->
            {% block logo %}
            <div class="col-12 col-sm order-1 order-sm-2 text-center text-lg-left">
            <h2>Logo Here</h2>
                <a class="navbar-brand d-none d-lg-inline Anuket-Text" href={% url 'dashboard:index' %}>
                    Laas Dashboard
                </a>
            </div>
            {% endblock logo %}
            <!-- Sidebar button -->
            <div class="col-6 col-sm-2 d-flex order-1 order-lg-3 d-lg-none">
                <button class="btn border mx-auto" type="button" data-toggle="collapse" data-target="#sidebar"
                    aria-expanded="false" aria-controls="sidebar">
                    <i class="fas fa-bars d-inline"></i>
                </button>
            </div>
            <!-- Login dropdown -->
            <div class="col-6 col-sm-2 order-3 d-flex">
                <ul class="nav mx-auto mr-sm-0">
                    <li class="dropdown ml-auto">
			{% block userDropDownText %}
                        <a class="nav-link p-0 p-2 Anuket-Text" data-toggle="dropdown" href="#">
                            {% if request.user.username %}
                                {{request.user.username}}
                            {% else %}
                                <i class="fas fa-user"></i>
                            {% endif %}
                            <i class="fas fa-caret-down rotate"></i>
                        </a>
			{% endblock userDropDownText %}
                        <div class="dropdown-menu dropdown-menu-right">
                            {% if LFID %}
                                {% if user.is_authenticated %}
                                <a href="{% url 'account:settings' %}" class="dropdown-item Anuket-Text">
                                    <i class="fas fa-cog"></i>
                                        Settings
                                </a>
                                <a id="logout_btn" href="#" method="post" class="dropdown-item Anuket-Text">
                                    <i class="fas fa-sign-out-alt"></i>
                                        Logout
                                </a>
                                <form id="logout_form" action="{% url 'oidc_logout' %}" method="post" style="visibility: hidden;">
                                    {% csrf_token %}
                                    <input type="submit" value="logout">
                                </form>
                                <script>
                                    const logout_btn = document.getElementById("logout_btn");

                                    const logout_form = document.getElementById("logout_form");

                                    logout_btn.onclick = function() { logout_form.submit(); };
                                </script>
                                {% else %}
                                <a href="{% url 'oidc_authentication_init' %}" class="dropdown-item Anuket-Text">
                                    <i class="fas fa-sign-in-alt"></i>
                                        Login with LFID
                                </a>
                                {% endif %}
                            {% else %}
                                {% if user.is_authenticated %}
                                    <a href="{% url 'account:settings' %}" class="dropdown-item Anuket-Text">
                                        <i class="fas fa-cog"></i>
                                        Settings
                                    </a>
                                    <a href="{% url 'account:logout' %}?next={{ request.path }}" class="dropdown-item Anuket-Text">
                                        <i class="fas fa-sign-out-alt"></i>
                                        Logout
                                    </a>
                                {% else %}
                                    <a href="{% url 'account:login' %}" class="dropdown-item Anuket-Text">
                                        <i class="fas fa-sign-in-alt"></i>
                                        Login with Jira
                                    </a>
                                {% endif %}
                            {% endif %}
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <!-- Page Content -->
    <div class="container-fluid d-flex flex-grow-1 px-0 align-items-start flex-column">
        <div class="row flex-grow-1 w-100 mx-0 align-content-start flex-lg-grow-1">
            <div class="col-12 col-lg-auto px-0 border-right border-left bg-light" role="navigation">
                <nav class="navbar navbar-expand-lg border-bottom p-0 w-100 sidebar">
                    <div class="collapse navbar-collapse" id="sidebar">
                        <div class="list-group list-group-flush w-100 ">
                            <a href="/" class="list-group-item list-group-item-action nav-bg">
                                Home
                            </a>
                            {% block dropDown %}
                            <a class="list-group-item list-group-item-action nav-bg" data-toggle="collapse"
                                href="#createList" role="button">
                                Create <i class="fas fa-angle-down rotate"></i>
                            </a>
                            <div class="collapse" id="createList">
                                <a href="/booking/quick/" class="list-group-item list-group-item-action list-group-item-secondary dropDown-bg">
                                    Express Booking
                                </a>
                                <a href="#" onclick="create_workflow(0)" class="list-group-item list-group-item-action list-group-item-secondary dropDown-bg">
                                    Book a Pod
                                </a>
                                <a href="#" onclick="create_workflow(1)" class="list-group-item list-group-item-action list-group-item-secondary dropDown-bg">
                                    Design a Pod
                                </a>
                                <a href="#" onclick="create_workflow(2)" class="list-group-item list-group-item-action list-group-item-secondary dropDown-bg">
                                    Create a Snapshot
                                </a>
                                <a href="#" onclick="create_workflow(3)" class="list-group-item list-group-item-action list-group-item-secondary dropDown-bg">
                                    Configure Anuket
                                </a>
                            </div>
                            {% endblock dropDown %}
                            <a href="{% url 'resource:hosts' %}" class="list-group-item list-group-item-action nav-bg">
                                Hosts
                            </a>
                            {% if user.is_authenticated %}
                                <a href="{% url 'account:users' %}" class="list-group-item list-group-item-action nav-bg">
                                    User List
                                </a>
                            {% endif %}
                            <a href="{% url 'booking:list' %}" class="list-group-item list-group-item-action nav-bg">
                                Booking List
                            </a>
                            <a href="{% url 'booking:stats' %}" class="list-group-item list-group-item-action nav-bg">
                                Booking Statistics
                            </a>
                            <a class="list-group-item list-group-item-action nav-bg" data-toggle="collapse"
                                href="#accountList" role="button">
                                Account <i class="fas fa-angle-down rotate"></i>
                            </a>
                            <div class="collapse" id="accountList">
                                <a href="{% url 'account:my-resources' %}" class="list-group-item list-group-item-action list-group-item-secondary dropDown-bg">
                                    My Resources
                                </a>
                                <a href="{% url 'account:my-bookings' %}" class="list-group-item list-group-item-action list-group-item-secondary dropDown-bg">
                                    My Bookings
                                </a>
                                <a href="{% url 'account:my-configurations' %}" class="list-group-item list-group-item-action list-group-item-secondary dropDown-bg">
                                    My Configurations
                                </a>
                                <a href="{% url 'account:my-images' %}" class="list-group-item list-group-item-action list-group-item-secondary dropDown-bg">
                                    My Snapshots
                                </a>
                            </div>
                            <a href="{% url 'dashboard:all_labs' %}" class="list-group-item list-group-item-action nav-bg">
                                Lab Info
                            </a>
                            <a href="{% url 'notifier:messages' %}" class="list-group-item list-group-item-action nav-bg">
                                Inbox
                            </a>
                        </div>
                    </div>
                </nav>
            </div>
            <div class="col overflow-auto flex-grow-1 d-flex flex-column h-100">
                {% if title %}
                <div class="row flex-shrink-1">
                    <div class="col-lg-12">
                        <h1 class="page-header">{{ title }}</h1>
                    </div>
                </div>
                {% endif %}
                {% if messages %}
                    <div id="bsm" class="mt-4">{% bootstrap_messages %}</div>
                {% endif %}
                <!-- Content block placed here -->
                {% block content %}
                {% endblock content %}
            </div>
        </div>
    </div>
</div>
{% endblock basecontent %}

src/templates/base/layout.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    {% block head-title %}
    <title>Anuket Laas {{ title }}</title>
    {% endblock head-title %}

    <!-- jQuery -->
    <script src="{% static "node_modules/jquery/dist/jquery.min.js" %}"></script>

    <!-- Bootstrap Core CSS -->
    <link href="{% static "node_modules/bootstrap/dist/css/bootstrap.min.css" %}"
          rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{% static "node_modules/@fortawesome/fontawesome-free/css/all.min.css" %}"
          rel="stylesheet" type="text/css">

    <link href="{% static "css/base.css" %}" rel="stylesheet">

    <!-- Favicon -->
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}">

    {% block extrahead %}
    {% endblock extrahead %}

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

{% block extrastyle %}
{% endblock extrastyle %}

<body>
{% block basecontent %}
{% endblock basecontent %}

<!-- Popper.js -->
<script src="{% static "node_modules/popper.js/dist/umd/popper.min.js" %}"></script>
<!-- Bootstrap Core JavaScript -->
<script src="{% static "node_modules/bootstrap/dist/js/bootstrap.min.js" %}"></script>

{% block extrajs %}
{% endblock extrajs %}
</body>
</html>